branch-defaults:
  main:
    environment: PDFSummarizer-dev
    group_suffix: null
environment-defaults:
  PDFSummarizer-dev:
    branch: main
    repository: PDFSummarizer
global:
  application_name: PDFSummarizer
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: PDFSummarizer
  sc: git
  workspace_type: Application
